x = input('Escreva algo:')
print('é número?')
print(x.isnumeric())
print('é letra?')
print(x.isalpha())
print('é número ou/e letra?')
print(x.isalnum())
print('é minusculo?')
print(x.islower())
print('é maiusculo?')
print(x.isupper())
print('é só espaços?')
print(x.isspace())
print('está capitalizada?')
print(x.istitle())
print('Seu tipo primitivo é:')
print(type(x))
print(x, ',espero que tenha gostado.')
